services:
  db_postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    ports:
      - "6543:5432"

  checkinapi:
    image: checkinapi
    ports:
      - 8081:8081
    build: .
    depends_on:
      - db

volumes:
  postgresql-data:
