name: Deploy

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1.1
        with:
          app-name: "airline-checkin-test"
          api-key: "${{secrets.HEROKU_API_KEY}}"
          
